name: Build, Publish and Deploy Docker image for production

# Configura el workflow para que se ejecute cada vez que se haga push a la rama main.
on:
  push:
    branches:
      - main

# Define dos variables de entorno personalizadas para el workflow. Estas se usan para el dominio del registro de contenedores y un nombre para la imagen Docker que este workflow construye.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-prod

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Configura los permisos otorgados al GITHUB_TOKEN para las acciones en este trabajo.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Usa la acción docker/login-action para iniciar sesión en el registro de contenedores usando la cuenta y contraseña que publicará los paquetes. Una vez publicados, los paquetes se asignan al alcance de la cuenta definida aquí.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PUBLISH_TOKEN }}

      # Este paso usa docker/metadata-action para extraer etiquetas y etiquetas que se aplicarán a la imagen especificada. El id "meta" permite que la salida de este paso se refiera en un paso posterior. El valor de las imágenes proporciona el nombre base para las etiquetas y etiquetas.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'

      # Este paso usa la acción docker/build-push-action para construir la imagen, basada en el Dockerfile de tu repositorio. Si la construcción tiene éxito, empuja la imagen a GitHub Packages.
      # Usa el parámetro context para definir el contexto de la construcción como el conjunto de archivos ubicados en la ruta especificada. Para más información, vea "[Usage](https://github.com/docker/build-push-action#usage)" en el README del repositorio docker/build-push-action.
      # Usa los parámetros tags y labels para etiquetar y etiquetar la imagen con la salida del paso "meta".
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            USERNAME=${{ secrets.USERNAME }}
            TOKEN=${{ secrets.PUBLISH_TOKEN }}


      # Este paso genera una atestación de artefactos para la imagen, que es una declaración infalsificable sobre dónde y cómo se construyó. Aumenta la seguridad de la cadena de suministro para las personas que consumen la imagen. Para más información, vea "[AUTOTITLE](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds)."
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}'
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Production
        run: |
          ssh ingsisAHRE@${{ secrets.PROD_IP }} << 'EOF'
            cd snippetInfra
            sudo su
            docker-compose -f docker-compose.prod.yml pull snippet_operations
            docker-compose -f docker-compose.prod.yml up -d snippet_operations
            docker image prune -f
          EOF
